In [1]:
#1. 
import numpy as np

zero_array = np.zeros(10)

print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#2.
arry_rannge10to49 = np.arange (10,50)

array_type = arry_rannge10to49.astype(float)

print(array_type)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [5]:
#3.
matrix_2x2_ones= np.ones((2,2), dtype= int)

print(matrix_2x2_ones)

[[1 1]
 [1 1]]


In [6]:
#4.
matrix_3x2_ones= np.ones((3,2), dtype= int)

print(matrix_3x2_ones)

[[1 1]
 [1 1]
 [1 1]]


In [7]:
#5.
X = np.array([[1, 2, 3], [4, 5, 6]])

same_like_X = np.ones_like(X)

print(same_like_X)

[[1 1 1]
 [1 1 1]]


In [8]:
#6.
X = np.array([[1, 2, 3], [4, 5, 6]])

same_like_X = np.zeros_like(X)

print(same_like_X)

[[0 0 0]
 [0 0 0]]


In [17]:
#7.
matrix_4x4_fives = np.full((4, 4), 5, dtype=int)

print(matrix_4x4_fives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
#8.
X = np.array([[1, 2, 3], [4, 5, 6]])

sevens_like_X = np.full_like(X, 7)

print(sevens_like_X)

[[7 7 7]
 [7 7 7]]


In [11]:
#9.

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#10.

random_array = np.random.randint(1, 11, size=3)

print(random_array)

[4 5 3]


In [13]:
#11.

random_float_matrix = np.random.rand(3, 3, 3)

print(random_float_matrix)

[[[0.7870164  0.2969673  0.0087946 ]
  [0.61302265 0.16514111 0.4043614 ]
  [0.57625989 0.0723541  0.89399304]]

 [[0.79987155 0.17096349 0.65734698]
  [0.64081307 0.14174406 0.27125854]
  [0.33392486 0.40850645 0.89363251]]

 [[0.71774991 0.85304039 0.75225322]
  [0.29309723 0.72618062 0.44232273]
  [0.401163   0.72437603 0.51715689]]]


In [14]:
#12.
array_1_to_10 = np.arange(1, 11)

print(array_1_to_10)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
#13.
array_odd_numbers = np.arange(1, 11, step=2)

print(array_odd_numbers)

[1 3 5 7 9]


In [19]:
#14.
array_descending = np.arange(10, 0, -1)

print(array_descending)

[10  9  8  7  6  5  4  3  2  1]


In [21]:
#15. 

array_0_to_8 = np.arange(9)

# Reshape the 1-dimensional array into a 3x3 matrix
matrix_3x3 = array_0_to_8.reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
#Array Indexing 
X = np.array(['A', 'B', 'C', 'D', 'E'])

# Access the first element of the array
first_element = X[0]

print(first_element)

A


In [23]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

# Access the last element of the array
last_element = X[-1]

print(last_element)

E


In [24]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

# Access the first three elements of the array
first_three_elements = X[:3]

print(first_three_elements)

['A' 'B' 'C']


In [25]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

# Show all middle elements (excluding the first and last)
middle_elements = X[1:-1]

print(middle_elements)

['B' 'C' 'D']


In [26]:
X = np.array(['A', 'B', 'C', 'D', 'E'])

# Show the elements in reverse position
reverse_elements = X[::-1]

print(reverse_elements)

['E' 'D' 'C' 'B' 'A']


In [27]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the elements of the first row
first_row_elements = X[0, :]

print(first_row_elements)

[1 2 3 4]


In [28]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the elements of the last row
last_row_elements = X[-1, :]

print(last_row_elements)

[13 14 15 16]


In [29]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the first element of the first row
first_element_first_row = X[0, 0]

print(first_element_first_row)

1


In [30]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the last element of the last row
last_element_last_row = X[-1, -1]

print(last_element_last_row)

16


In [ ]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the first two elements on the first two rows
first_two_elements_first_two_rows = X[:2, :2]

print(first_two_elements_first_two_rows)

In [31]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Show the last two elements on the last two rows
last_two_elements_last_two_rows = X[-2:, -2:]

print(last_two_elements_last_two_rows)

[[11 12]
 [15 16]]


In [32]:
#Array manipulation
X = np.array([-5, -3, 0, 10, 40])

# Convert the array to float
X_float = X.astype(float)

print(X_float)

[-5. -3.  0. 10. 40.]


In [33]:
X = np.array([1, 2, 3, 4, 5])

# Reverse the array through indexing
reversed_X = X[::-1]

print(reversed_X)

[5 4 3 2 1]


In [34]:
X = np.zeros(10)

# Set the fifth element to 1
X[4] = 1

print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [35]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Change the last row to have all elements equal to 1
X[-1, :] = 1

print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [36]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Add 5 to every element
X_plus_5 = X + 5

print(X_plus_5)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
